### ISSUE TITLE
Stata18

### ISSUE THREAD

**Issue by friosavila** [hugetim/nbstata#23] opened 2023-04-27 02:43 UTC
Hi Tim,
Quick question. Is there anything special one would need to do so nbstata could work with Stata18?
Thank you!
F

**Comment by hugetim** [comment] 2023-04-27 12:17
I don't see anything in the changes they list that should cause a problem, so I'm confident it will continue working. The only [changes listed to the Python API](https://www.stata.com/help.cgi?whatsnew17to18#NewP) are to do with missing values and new frame aliases. But I haven't tested it yet, so please let us know if you encounter any issues.

**Comment by friosavila** [comment] 2023-04-27 13:28
Will do.
Although a follow up question. Right now nbstata calls on Stata17. is there
anything on nbstata configuration I would need to change?
Thank you

**Comment by hugetim** [comment] 2023-04-27 20:11
Right, if you have multiple versions of Stata installed, you will have to specify which one you want in the config file to be sure.

Also, now that I think of it, there are [one](https://github.com/hugetim/nbstata/blob/9ae2a89c9ada428781bef943a727f0247295dadd/nbstata/code_utils.py#L151) or two places where version 17.0 may be hardcoded, but it shouldn't cause any major issues. Let me know if you run into any issues.

**Comment by hugetim** [comment] 2023-04-28 01:14
> It was odd, however, that I couldn't change the configuration using %set
 
Right, I should add that to the docs if it's not there: it can't be changed with %set because Stata is already launched and running once the kernel is started. It's too late to change that config value then (without restarting the Stata session, which is not usually what %set does).

💡I guess there should also be an error message that explains that if you try to use %set for this.

**Comment by hugetim** [comment] 2023-08-23 15:46
> 💡I guess there should also be an error message that explains that if you try to use %set for this.

This was addressed by https://github.com/hugetim/nbstata/commit/6af51cd03df80d3e0b66bb9ef6552602d8e96099, released as part of [v0.6.3](https://github.com/hugetim/nbstata/releases/tag/v0.6.3). I've also confirmed there are no other issues with using Stata 18, so I'm closing this.

**Closed by hugetim** 2023-08-23 15:46 UTC
Labels: enhancement
